### ISSUE TITLE
Handle rejection if ResinOS is not able to log in

### ISSUE THREAD

**Issue by horia-delicoti** [resin-io/resinos-tests#188]
If the resinos fails to login, the test suite fails with:
```
Teardown...
Removing application: mochaTest_rfaAy
Delete SSH key with label: mochaTest_rfaAy
Delete SSH key with label: mochaTest_rfaAy
Delete SSH key with label: mochaTest_rfaAy
Delete SSH key with label: mochaTest_rfaAy
Delete SSH key with label: mochaTest_rfaAy
(node:79) UnhandledPromiseRejectionWarning: Error: operation timed out after 6014 ms, 5 tries with error: You have to log in
    at /usr/app/node_modules/bluebird-retry/lib/bluebird-retry.js:109:35
    at tryCatcher (/usr/app/node_modules/bluebird/js/release/util.js:16:23)
    at /usr/app/node_modules/bluebird/js/release/catch_filter.js:24:41
    at tryCatcher (/usr/app/node_modules/bluebird/js/release/util.js:16:23)
```

**Comment by horia-delicoti** [comment]
@jviotti @telphan Very important ^
